name: Deploy-gorzdrav_spb_checkbot

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Deploy_scheduler:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: deploy via ssh
      uses: appleboy/ssh-action@master
      env:
        BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        CONTAINER_NAME: telegram_gorzdrav_spb
      with:
        host: ${{ secrets.DEPLOY_SERVER_HOST }}
        username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
        password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
        port: ${{ secrets.DEPLOY_SERVER_PORT }}
        script_stop: true
        envs: TELEGRAM_BOT_TOKEN,CONTAINER_NAME
        script: |
          cd /opt/gorzdrav_spb_checkbot
          git pull
          docker build . -t gorzdrav_spb_checkbot
          docker stop $CONTAINER_NAME
          docker rm $CONTAINER_NAME
          docker run -d --restart unless-stopped --name $CONTAINER_NAME -e bot_token="$TELEGRAM_BOT_TOKEN" gorzdrav_spb_checkbot
          sleep 3
          docker logs $CONTAINER_NAME 2>&1 | grep 'Bot started'
          
        
